### ISSUE TITLE
Unable to resolve tagplus5.github.io

### ISSUE THREAD

**Issue by philippw** [tagplus5/vscode-ppa#1]
Hi,

When I execute the first command, I get the following error"
`$ sudo wget -O - https://tagplus5.github.io/vscode-ppa/ubuntu/gpg.key | sudo apt-key add -
--2016-11-28 15:13:24--  https://tagplus5.github.io/vscode-ppa/ubuntu/gpg.key
Resolving tagplus5.github.io (tagplus5.github.io)... failed: Name or service not known.
**wget: unable to resolve host address ‘tagplus5.github.io’**
gpg: no valid OpenPGP data found.`

Has the host been removed? Is this project still actively maintained?

Thanks in advance,
Philipp

**Comment by tagplus5** [comment]
Hi. I try reproduce error.

![image](https://cloud.githubusercontent.com/assets/2699260/20671980/475b6bb2-b588-11e6-8699-e2629218bdfb.png)

**Comment by tagplus5** [comment]
I create https://tagplus5.github.io 
Please try again.

**Comment by MrLuisAmador** [comment]
@tagplus5 

Thanks for the ppa. I just used it to install 1.8 right now. Working good on:

![linux_distro](https://cloud.githubusercontent.com/assets/6766589/21207592/f4617d6e-c236-11e6-9df9-158f2df17798.png)

![vscode_version](https://cloud.githubusercontent.com/assets/6766589/21207595/fba807aa-c236-11e6-8236-f254b462ee53.png)

**Comment by philippw** [comment]
Thanks for the fix!
