### ISSUE TITLE
Documentation on how to use github repo as PPA

### ISSUE THREAD

**Issue by athrunsun** [tagplus5/vscode-ppa#6]
Hi,

Thanks for making this repo in advance.

I think it is really useful to use github repo as PPA, not only because my network connections to github are way faster then ppa.launchpad.net, but also good to know the insides of how to update/push, etc. (through your `update.sh`, `push.sh`) to keep a PPA update to date.

Could you share how to use a github repo as PPA like this one in your README? Including how to create a gpg key, how your shell scripts work. Would really appreciate this since I have several softwares that's not included in my distro's package management system, and I want to host their deb on my own PPA.

Thanks!

**Comment by assafmo** [comment]
This will be awesome!

**Comment by assafmo** [comment]
@athrunsun I think I figured it out.  
I've implemented it in https://github.com/assafmo/ppa.

I think I'll write a tutorial on how to create your own in a few days.

**Comment by assafmo** [comment]
@athrunsun 
https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html
:smile:

**Comment by athrunsun** [comment]
@assafmo Thank you so much! This is really useful! I've successfully created my own PPA [here](https://github.com/athrunsun/ppa).

**Comment by assafmo** [comment]
@athrunsun This is awesome!
I'm glad you found it useful 😎
