### ISSUE TITLE
License of the packages

### ISSUE THREAD

**Issue by tormol** [tagplus5/vscode-ppa#7]
Are they MIT-licensed or under the proprietary https://code.visualstudio.com/license ?
In other words, do you build from source or package microsoft's binary downloads?

(See https://github.com/Microsoft/vscode/issues/60#issuecomment-161792005 and https://github.com/Microsoft/vscode/issues/17996)

**Comment by tagplus5** [comment]
I package microsoft's binary downloads.

**Comment by tormol** [comment]
:disappointed: There is no way around building it myself then. ¯\\\_(ツ)\_/¯

Could you document this in the readme?

**Comment by ghost** [comment]
https://github.com/Microsoft/vscode/issues/17996#issuecomment-466454627
